FROM node:20 AS builder

WORKDIR /app
COPY . .
ENV NODE_ENV production
RUN yarn set version berry
RUN yarn workspaces focus --all --production
RUN yarn add @prisma/client
RUN yarn prisma generate
RUN yarn run build

FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/yarn.lock ./yarn.lock
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.yarn ./.yarn
COPY --from=builder /app/.yarnrc.yml ./.yarnrc.yml
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/.env ./.env
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000

CMD ["yarn","start:prod"]