# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - /var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
