name: BE Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'BE/**'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make ENV
        working-directory: ./BE
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env

      - name: Build Docker image
        working-directory: ./BE
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/was -f dev.dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        working-directory: ./BE
        run: docker push ${{ secrets.DOCKER_USERNAME }}/was

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Delete old docker image
        run: docker image prune -af

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/was

      - name: Stop running container
        run: docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/was )

      - name: Run Docker image
        run: docker run -d --name was --network my_network ${{ secrets.DOCKER_USERNAME }}/was:latest
