name: BE Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for BE directory changes
      id: check_be_changes
      run: |
        if [[ $(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^BE/') ]]; then
          echo "::set-output name=be_changes::true"
        else
          echo "::set-output name=be_changes::false"
        fi

    - name: Make ENV
      working-directory: ./BE
      run: |
        if [[ "${{ steps.check_be_changes.outputs.be_changes }}" == "false" ]]; then
          echo "No changes in BE directory detected. Skipping BE build."
          exit 0
        fi
        touch .env
        echo "${{ secrets.ENV }}" > .env
      shell: bash

    - name: Build Docker image
      working-directory: ./BE
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/was -f dev.dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      working-directory: ./BE
      run: docker push ${{ secrets.DOCKER_USERNAME }}/was
